# Generated by Django 4.2.2 on 2023-06-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=50)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'ordering': ['-prioridad', 'texto'],
            },
        ),
    ]
