# Generated by Django 4.2.1 on 2023-06-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['prioridad', 'texto']},
        ),
    ]
